language: rust
rust:
    - stable
    - beta
    - nightly
dist: zesty
addons:
  apt:
    packages:
    - cmake
install:
  - sudo apt-get install cmake
  - sudo apt-get install libXxf86vm-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
script:
  - cargo build
  - cargo test
