env:
  global:
    - secure: NvjvFnlJ2Lic4kI6ugcVNrAxBNNabl4oWXxcZdCy8Dfmp6yeMuVdAjHGltua/YsFlHUhEWxBYNX8dBkEv5F/OjJ/xE6880EiAKHjYtSecSf8c2VmOd//LePb8tgmyPZeHY0eGzNi0Q9tYKGqHW317c+cRlWgjyXgeAm9YrdmKVM=
language: c
install:
  - curl -s http://www.rust-lang.org/rustup.sh | sudo sh
  - sudo apt-get install libXxf86vm-dev
script:
  - sudo apt-get update
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - make
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
