env:
  global:
    - secure: NvjvFnlJ2Lic4kI6ugcVNrAxBNNabl4oWXxcZdCy8Dfmp6yeMuVdAjHGltua/YsFlHUhEWxBYNX8dBkEv5F/OjJ/xE6880EiAKHjYtSecSf8c2VmOd//LePb8tgmyPZeHY0eGzNi0Q9tYKGqHW317c+cRlWgjyXgeAm9YrdmKVM=
language: c
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - sudo apt-get install libXxf86vm-dev
script:
  - sudo apt-get update
  - sudo apt-get install cargo
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - make
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
