[package]
name    = "kiss3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "kiss3d"
path = "src/lib.rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide]
git = "https://github.com/sebcrozet/ncollide"
features = [ "3df32" ]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
 
[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

[dependencies.stb_image]
git = "https://github.com/servo/rust-stb-image"
