[package]
name    = "kiss3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "3D graphics engine for Rust."
repository = "https://github.com/sebcrozet/kiss3d"
readme = "README.md"
keywords = [ "3D", "graphics", "OpenGL", "KISS" ]
license = "BSD-3-Clause"

[lib]
name = "kiss3d"
path = "src/lib.rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide_procedural]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
 
[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

[dependencies.stb_image]
git = "https://github.com/servo/rust-stb-image"

[dependencies.time]
git = "https://github.com/rust-lang/time"
