[package]
name    = "kiss3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[[lib]]
name       = "kiss3d"
path       = "src/lib.rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide3df32]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.gl]
git = "https://github.com/sebcrozet/gl-rs"
 
[dependencies.glfw]
git = "https://github.com/sebcrozet/glfw-rs"

[dependencies.rust-freetype]
git = "https://github.com/sebcrozet/rust-freetype"

[dependencies.stb_image]
git = "https://github.com/sebcrozet/rust-stb-image"
