[package]
name    = "kiss3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[[lib]]
name       = "kiss3d"
path       = "src/lib.rs"
crate_type = [ "dylib", "rlib" ]

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide3df32]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.gl]
git = "https://github.com/sebcrozet/gl-rs"
 
[dependencies.glfw]
git = "https://github.com/sebcrozet/glfw-rs"

[dependencies.rust-freetype]
git = "https://github.com/sebcrozet/rust-freetype"

[dependencies.rust-stb-image]
git = "https://github.com/sebcrozet/rust-stb-image"

[[bin]]
name = "add_remove"
path = "./examples/add_remove.rs"

[[bin]]
name = "camera"
path = "./examples/camera.rs"

[[bin]]
name = "cube"
path = "./examples/cube.rs"

[[bin]]
name = "custom_material"
path = "./examples/custom_material.rs"

[[bin]]
name = "custom_mesh"
path = "./examples/custom_mesh.rs"

[[bin]]
name = "custom_mesh_shared"
path = "./examples/custom_mesh_shared.rs"

[[bin]]
name = "event"
path = "./examples/event.rs"

[[bin]]
name = "group"
path = "./examples/group.rs"

[[bin]]
name = "lines"
path = "./examples/lines.rs"

[[bin]]
name = "obj"
path = "./examples/obj.rs"

[[bin]]
name = "points"
path = "./examples/points.rs"

[[bin]]
name = "post_processing"
path = "./examples/post_processing.rs"

[[bin]]
name = "primitives"
path = "./examples/primitives.rs"

[[bin]]
name = "primitives_scale"
path = "./examples/primitives_scale.rs"

[[bin]]
name = "procedural"
path = "./examples/procedural.rs"

[[bin]]
name = "quad"
path = "./examples/quad.rs"

[[bin]]
name = "relativity"
path = "./examples/relativity.rs"

[[bin]]
name = "stereo"
path = "./examples/stereo.rs"

[[bin]]
name = "text"
path = "./examples/text.rs"

[[bin]]
name = "texturing"
path = "./examples/texturing.rs"

[[bin]]
name = "window"
path = "./examples/window.rs"

[[bin]]
name = "wireframe"
path = "./examples/wireframe.rs"
